### ISSUE TITLE
Not works for Steam Deck

### ISSUE THREAD

**Issue by Cr0WD** [Lyall/BipedFix#1]
it looks like the steam deck has a different folder structure.
the configuration file is not created. 
in addition, the system did not offer to replace the files when copying 
![image](https://github.com/Lyall/BipedFix/assets/10212701/924e4a2e-9736-48d7-a08e-eab27654b1e6)

**Comment by Lyall** [comment]
Can you try changing the Steam launch options for the game to this? `WINEDLLOVERRIDES="winhttp=n,b" %command%`

![image](https://github.com/Lyall/BipedFix/assets/695941/90403e74-e2a2-481f-a517-db90786103ca)

**Comment by Cr0WD** [comment]
@Lyall thanks, it works like a charm!
